### ISSUE TITLE
[ECE] Deploy docker container for ES diagnostics

### ISSUE THREAD

**Issue by agopiola** [elastic/ece-support-diagnostics#112]
This request would provide a an easier way of collecting diagnostic data against and ECK cluster by simply including the current  diagnostic bundle within a container hosted within Elastic cloud environment.  hosts within our.  Unfortunately downloading .zip and rarely .tar files from GitHub are not allowed.

There may be other Elastic customers experiencing similar issues, and in doing so, it might also lessen the duration of support related cases.

**Use case. Why is this important?**

1. It would lessen the time it take to gather the required information needed for a support related call via an "easy-button"
2. Security controls do not let us download .zip files, and rarely .tar from Github

**Kubernetes information:**
**Products/Versions:** Elastic Stack 7.14.1, ECK 1.7.1

**Comment by jguay** [comment]
@agopiola It seems this enhancement issue is not about ECE diagnostics but [ECK diagnostics](https://github.com/elastic/eck-diagnostics) ?

**Comment by jguay** [comment]
Closing this issue as it seems it is not about ECE support diagnostics.
