### ISSUE TITLE
Offer a logs only collection option for when ECE API is unavailable

### ISSUE THREAD

**Issue by VimCommando** [elastic/ece-support-diagnostics#118]
When an ECE environment is so broken the API is unavailable, sometimes it is still very useful to collect the most recent logs.

Offering a `--logs-only` argument (or similar) would allow us to generate a bundle without the API responses.

**Comment by jguay** [comment]
`./ece-diagnostics.sh -u admin` triggers API collection (with `-e <coordinator IP>` if not run on a coordinator as it default to `localhost`), omit `-u admin` and no API call will be attempted

As a note; the golang version of ECE diagnostics which will replace this current bash project - we will collect APIs by default (no setting needed) with an option to disable it explicitly but failure to collect API should not fail the execution of the diagnostics (in bash version if `-e localhost` or `-e` omitted and the is no answer we fail diagnostics as this was common when ECE diag was run from a non-coordinator, most other issues do not cause ECE diag to fail)
