### ISSUE TITLE
Collect ECE upgrade logs if present

### ISSUE THREAD

**Issue by geekpete** [elastic/ece-support-diagnostics#126]
As mentioned in the Docs, there's two produced log files from running the upgrade process:
https://www.elastic.co/guide/en/cloud-enterprise/current/ece-issues.html#ece-troubleshooting-upgrade

>HOST_STORAGE_PATH/logs/upgrader-logs/monitor.log
    Available on the host where you initiated the upgrade process. This log file can help you pinpoint the host where an upgrade issue occurred or where in the overall upgrade process a failure happened. 
  HOST_STORAGE_PATH/logs/upgrader-logs/upgrader.log
    Available on every host that attempted the upgrade. This log file can tell you about the specific issues that caused the upgrade to fail on a host. 

that would be great to collect on any ECE host that has them where the ECE diag is run.

**Comment by jguay** [comment]
Thank you for raising this @geekpete

I think we already collect those logs in bash ece diagnostics as far as I know, depending on : 
```
-lh|--log-filter-hours #oldest file to collect in hours (default:72). also applied to docker logs
```

Note the current ECE diagnostics bash is deprecated so I don't think we'll implement any enhancement now for the deprecated tool - though if what you are suggesting is that for this type of logs we should ignore the timestamp of the files, this is a good enhancement to raise for the [new tool](https://www.elastic.co/guide/en/cloud-enterprise/3.4/ece-run-ece-diagnostics.html) part of ECE main codebase (which currently works same way as far as I understand), is that what you had in mind ?

**Comment by geekpete** [comment]
Also looks like we already capture these files in the new ECE diag tool:

```
$ ls -lha
total 1.3M
drwxrwxr-x. 17 elastic elastic 4.0K Jan  3 04:38 .
drwxrwxr-x.  7 elastic elastic  130 Jan  3 04:38 ..
drwxrwxr-x.  3 elastic elastic  164 Jan  3 04:38 admin-console
drwxrwxr-x.  3 elastic elastic  152 Jan  3 04:38 allocator
drwxrwxr-x.  3 elastic elastic  185 Jan  3 04:38 allocator-metricbeat
drwxrwxr-x.  3 elastic elastic  161 Jan  3 04:38 beats-runner
drwxrwxr-x.  3 elastic elastic  152 Jan  3 04:38 blueprint
-rw-r--r--.  1 elastic elastic  30K Jan  3 04:00 bootstrap.log
drwxrwxr-x.  4 elastic elastic  188 Jan  3 04:38 client-forwarder
drwxrwxr-x.  2 elastic elastic  137 Jan  3 04:38 cloud-ui
drwxrwxr-x.  3 elastic elastic  158 Jan  3 04:38 constructor
drwxrwxr-x.  2 elastic elastic  179 Jan  3 04:38 container-task-service
-rw-------.  1 elastic elastic  28K Jan  3 04:31 container-task-service.log
drwxrwxr-x.  3 elastic elastic  149 Jan  3 04:38 director
-rw-r--r--.  1 elastic elastic 1.1M Jan  3 04:34 director.log
-rw-r--r--.  1 elastic elastic  32K Jan  3 04:32 monitor.log
drwxrwxr-x.  3 elastic elastic  146 Jan  3 04:38 proxyv2
drwxrwxr-x.  3 elastic elastic  161 Jan  3 04:38 route-server
drwxrwxr-x.  4 elastic elastic   51 Jan  3 04:38 runner
drwxrwxr-x.  3 elastic elastic  179 Jan  3 04:38 services-forwarder
-rw-r--r--.  1 elastic elastic  93K Jan  3 04:27 upgrade.log
drwxrwxr-x.  4 elastic elastic  167 Jan  3 04:38 zookeeper
```

![2023-01-03_14-40](https://user-images.githubusercontent.com/2070843/210301039-590846a7-cc65-42cc-a31b-341ae38928ec.png)

So no need to log a new enhancement issue for this.
