### ISSUE TITLE
copy only recent files

### ISSUE THREAD

**Issue by nellicus** [elastic/ece-support-diagnostics#15]
as suggested by @jpcarey 

>we might consider is to not copy older data. It seems right now we copy everything, which can include weeks old data. It seems like we should only try to preserve now-5d or something like that (with maybe a `--full` option to grab everything)

**Comment by jpcarey** [comment]
the golang version of the diagnostic filters to both system logs and docker logs with a 72h filter:

**default value**:
https://github.com/elastic/ece-support-diagnostics/blob/f3b4d2eb4ba5455401d733c6bf61ac5167fa3ac0/cmd/ece-support-diagnostics/root.go#L178-L184

**system logs**:
https://github.com/elastic/ece-support-diagnostics/blob/9edb0542a8b02f2f3398d7ed6466c7acb731294d/collectors/systemLogs/systemLogs-collector.go#L124-L132

**docker logs**:
https://github.com/elastic/ece-support-diagnostics/blob/656312784e4a62069df4986ffa3d6aeea5cae73c/collectors/docker/docker-collector.go#L80
