### ISSUE TITLE
Fail or Notify if ECE storage is not found by the specified path 

### ISSUE THREAD

**Issue by yuri-tceretian** [elastic/ece-support-diagnostics#20]
Users often specify a custom storage directory for ECE, and when we ask them to run the script almost nobody specifies it, which makes the package be almost useless. 
The script should fail (or at least warn the user) if the storage is not found by the specified path (either default or explicitly specified).

**Comment by jpcarey** [comment]
this is fixed in the the golang version of the diagnostic:

https://github.com/elastic/ece-support-diagnostics/blob/0d6022c562fb9aafb3ff289cd836132faa2b653b/config/config.go#L51-L61
