### ISSUE TITLE
add dmesg output

### ISSUE THREAD

**Issue by jakommo** [elastic/ece-support-diagnostics#24]
It would be useful to get the `dmesg` output from the host the diag was executed on, i.e. to check for disk / filesystem errors on the host. 
Preferable `dmesg -T` which should be supported by all OS that we support for ECE.

**Comment by Leaf-Lin** [comment]
I've wanted this almost every capture :) 
Is there anyway to add this easily? @jakommo

**Comment by jakommo** [comment]
Should be easy to add. I try to do it later today. 
I thought we removed it from the none ECE support diag for some reason and thus I was not adding it here, but I just checked and [it's there](https://github.com/elastic/support-diagnostics/blob/bad8fe76f2d2be716c14ffc5455f8fb51d78d280/src/main/resources/diags.yml#L53), so should be fine to add it here as well. 
Just need to do some testing on the different supported OS to come up with the best set of params. Currently I'm leaning towards `sudo dmesg --ctime --time-format iso`
