### ISSUE TITLE
collect ECE license

### ISSUE THREAD

**Issue by jpcarey** [elastic/ece-support-diagnostics#28]
The ECE license should be included in the diagnostic.

https://github.com/elastic/ece-support-diagnostics/blob/8d1391829382e2721d8e1b3b452b4e94a1242a4b/config/auth.go#L33-L34

**Comment by immavalls** [comment]
Is it possible to capture the information? CSM reached out to me to know the usage of a customer, and it does not come in an ECE diagnostics, afaik.

**Comment by geekpete** [comment]
I've also had CSMs asking about customer usage, specifically currently used capacity vs total licensed capacity. This would be great to include/infer from a diagnostic especially if we can see the overall breakdown of what they're using their license for as far as different host types/instance types/deployments._
