### ISSUE TITLE
Collect instance configuration 

### ISSUE THREAD

**Issue by AndyHunt66** [elastic/ece-support-diagnostics#43]
It would be useful to have instance configuration information in the diags.
E.g the output of 
`GET /api/v1/platform/configuration/instances`
`GET /api/v1/deployments`

**Comment by jakommo** [comment]
Thanks @AndyHunt66. In addition to the instance configuration, it would also be good to get the deployment templates `GET /api/v1/platform/configuration/templates/deployments` to paint the full picture .
