### ISSUE TITLE
Support for log files in NDJSON format

### ISSUE THREAD

**Issue by yuri-tceretian** [elastic/ece-support-diagnostics#49]
Since PR https://github.com/elastic/cloud/pull/36621 was merged, all ECE services start writing logs in ndjson format. Apparently, the script ignores those files.

**Comment by henrikno** [comment]
Should be easy to fix by adding `-or "*.ndjson"` to 
https://github.com/elastic/ece-support-diagnostics/blob/bbbe3b64ab64ec57fc645b35d4f429f26775f6cb/diagnostics.sh#L198
