### ISSUE TITLE
Add 'mntr' ZK output to ECE diagnostics

### ISSUE THREAD

**Issue by mcpate** [elastic/ece-support-diagnostics#5]
We recently had an issue that investigation whittled down to a possible ZK issue. One of the key pieces of information that would have been nice to have was the state of ZK on the different Director nodes.

As the linked SDH mentions, it would've been great to know what the zk_node_count was for each of the ZK nodes and which ones thought they were leaders. Getting the diagnostics seems somewhat straightforward. It would be really nice if we could somehow include these in the diagnostics tool.

**Comment by jpcarey** [comment]
already in the golang version of the diagnostic. If the host it is running on has the `frc-zookeeper-servers-zookeeper` container, it will try to collect zookeeper's `mntr`

https://github.com/elastic/ece-support-diagnostics/blob/656312784e4a62069df4986ffa3d6aeea5cae73c/collectors/docker/docker-collector.go#L83-L86
&
https://github.com/elastic/ece-support-diagnostics/blob/9ab5602233e3dccf22be340099471d0870dbc4b3/collectors/zookeeper/zookeeper-collector.go
