### ISSUE TITLE
support diagnostics not working with protocol https and self signed certificate

### ISSUE THREAD

**Issue by 111andre111** [elastic/ece-support-diagnostics#55]
At the moment if ece diagnostics is executed against https instance to grab information about a particular cluster, ece diagnostics is not returning anything, because it transfers to routine `do_http_request` always protocol http and not https.
`./diagnostics.sh -e <ip> -x 12443 -y https -u <user> -p <password> -a -c <cluster>`

**Comment by jakommo** [comment]
Left a comment in https://github.com/elastic/ece-support-diagnostics/pull/56. I think it would be much better to use `--cacert <file> and --capath <dir>` and not `--insiecure` . 

A workaround for the current issue would be to add the custom CA to the OS cert trust store.
