### ISSUE TITLE
Add feature to collect logs from the Logging and Metrics cluster

### ISSUE THREAD

**Issue by jakommo** [elastic/ece-support-diagnostics#57]
The ES diag does support [extracting Monitoring and Metric](https://github.com/elastic/support-diagnostics#extracting-time-series-diagnostics-from-monitoring) data and then load it locally to investigate. 
It would be nice if the ECE diag had a similar feature to export:
* Logs and Metrics from the Logging and Metrics cluster, with:
  * Filter on timeframe to be exported
  * Index (pattern) to export for Logs
  * filter on deployment + instance id for Log and/or Metrics

If it uses the same format as the ES diag, we could re-use the import function for the metrics data.
For logs importing into an Elastic Stack is probably the best solution and we already have [filebeat modules](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-elasticsearch.html) for that

**Comment by jpcarey** [comment]
The Logging and Metrics cluster data was already included in the go rewrite of this tool, well over a year ago. That said, it will  be fun (and probably rather pointless) for someone to solve auth & elasticsearch scroll using bash.

**Comment by jakommo** [comment]
Thanks for getting back @jpcarey . I mainly open this to track it and wasn't thinking about adding this to the bash version, but good to know that the go version was already capable of this.

**Comment by jguay** [comment]
I will close this issue as bash ece diagnostics is deprecated and raise an issue internally to track this requirement for ECE diagnostics tooling
