### ISSUE TITLE
Add additional commands to the Deployment Diagnostic Tool

### ISSUE THREAD

**Issue by BobBlank12** [elastic/ece-support-diagnostics#66]
Just like: https://github.com/elastic/support-diagnostics/issues/444

Please include:
GET _cat/templates?v -- _this is needed because it will list the contents of GET _template and GET _index_template, however GET _template does not include the data from GET _index_template
GET _index_template
GET _component_template

Commands introduced in 7.8

**Comment by jguay** [comment]
@BobBlank12 It is technically possible to add commands from [ES](https://github.com/elastic/support-diagnostics/blob/main/src/main/resources/elastic-rest.yml), [kibana](https://github.com/elastic/support-diagnostics/blob/main/src/main/resources/kibana-rest.yml) diagnostics but at the moment customer would have to run the tool as ECE diagnostics does not query information from elasticsearch clusters.
We have APIs like `/api/v1//clusters/elasticsearch/:cluster_id/proxy/:elasticsearch_path` with GET/POST
There are internal issues also for ECE `Prepare Diagnostics` in `Operations` tab which depends on ECE version (part of admin console), was the issue related to this or were you suggesting that we proxy all the APIs and duplicate what elasticsearch/kibana diagnostics is doing ?

**Comment by BobBlank12** [comment]
Closing as there is already a known issue in the proper repo.  Thanks @jguay!
