### ISSUE TITLE
Capture certificate expiration and issuer in diagnostics

### ISSUE THREAD

**Issue by mcpate** [elastic/ece-support-diagnostics#70]
We recently had an SDH that was a bit complicated to troubleshoot. Eventually, we realized that the internal certificate expired which was causing the Proxy to reject requests from our internal services. It would be really nice if the diagnostics tool captured the expiration of the internal certs and the issuer so that we could check those things as top-level items when troubleshooting ECE issues. Having the certificate expiration in the ECE diagnostics might not always catch the problem (there are certain scenarios where _some_ services might be using an expired certificate and _some_ might not be), but in the cases where it does catch it we could save a lot of time troubleshooting.

The following is an example of how we ran `openssl` on the underlying host to verify the certificate expiration:
```
openssl x509 -in /mnt/data/elastic/ece-0-runner/services/route-server/managed/cert.pem -inform pem -noout -enddate cert.pem ca-file.pem
```

The following is an example of how we ran `openssl` on the underlying host to verify the issuer (which highlights whether the cert is our internal cert or one that the customer uploaded):
```
openssl x509 -in /mnt/data/elastic/ece-0-runner/services/route-server/managed/cert.pem -inform pem -noout -issuer
```

**Comment by jguay** [comment]
I am curious if you had suggestions on how to implement this @mcpate in case you have suggestions, do we have openssl command installed inside any ECE container ? I can code something to capture the information if openssl command is available on the ECE instance where the script run but `openssl` will most likely not be available/installed

I had a quick look and found the command inside ES container of 7.12 but not 6.8 but in any case I cannot use this anyhow as ECE diagnostics may not run from an allocator hence I have to assume only ECE image can be used... In ECE containers, I find some python libraries in folder called `openssl` but no CLI command so I assume we would need to run some python script using a container based on ece image

**Comment by jguay** [comment]
I had found these folders in ECE image : 
```
# find / -name openssl
/etc/pki/ca-trust/extracted/openssl
/usr/lib64/openssl
/usr/local/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl
/usr/local/lib64/python3.6/site-packages/cryptography/hazmat/bindings/openssl
```

This means cryptography module is installed in python3 but not OpenSSL 
```
$ ece_image="$(docker ps --format '{{.Image}}' --filter 'name=frc-runners-runner')"
$ docker run -it --rm --name 'ecediagtmp' -v "$cert_path:/tmp/cert.pem:ro" "$ece_image" python3 -c 'help("modules")' | grep -c "OpenSSL"
0
```

Hence all I think we need to include some binary file with ability to check certificate expiration as part of ECE diagnostics.

**Comment by jguay** [comment]
Ended up writing 2 small golang program to get certificate expiration from any *.pem file and for https://coordinator:12443
The openssl CLI would be cheaper but I assumed openssl may not be installed

**Comment by mcpate** [comment]
Hey there @jguay! Somehow I missed your ping above. Sorry about that! Glad to see I didn't hold you up. :)
