### ISSUE TITLE
Rename diagnostics.sh to make it clearer this is an ECE diagnostics tool

### ISSUE THREAD

**Issue by jguay** [elastic/ece-support-diagnostics#71]
Sometimes when asking for a diagnostics, a couple of users got confused about ECE or ES diagnostics, the scripts having the exact same file names is not helping

Such change is breaking so the README and any documentation mentioning ECE diagnostics should be updated to reflect the new name and maybe mention the old name for people who still use an old release

Any feedback if we should rename to `ece_diagnostics.sh` ? I am not aware of any automation relying on this name so I don't expect this to be breaking any external feature

**Comment by jakommo** [comment]
I'm +1 on renaming it as I've seen the same type of confusion across users.
