### ISSUE TITLE
Hardcoded ece_docker_registry in Docker/Logs

### ISSUE THREAD

**Issue by user-987654321** [elastic/ece-support-diagnostics#78]
In Docker/logs  files are created with the ece_docker_registry in the filename ie b430582734_frc_allocators-metricbeats-allocator-metricbeat__ **privateregistry.constso.com**_cloud-enterprise_elastic………...log

Do we really need the ece_docker_registry coded into a file name? the ece_docker_registry variable needs manually redacting after running the scrub tool because the scrub tool only removes data from within the file not the filename

**Comment by jguay** [comment]
I don't think there is any hard requirement to [filename containing the image name](https://github.com/elastic/ece-support-diagnostics/blob/v2.0.0/src/ece-diagnostics.sh#L258) at this point so we could not include it if this is causing any issue, marking this issue as Enhancement to be considered for future ece diag version.

The image name is collected inside [docker ps](https://github.com/elastic/ece-support-diagnostics/blob/v2.0.0/src/ece-diagnostics.sh#L272) and [docker images](https://github.com/elastic/ece-support-diagnostics/blob/v2.0.0/src/ece-diagnostics.sh#L280), it is important for support to know that installation is offline as this can lead to some mistakes/issues that are not possible on online installation

Could you just confirm what you use for scrubbing as ece diagnostics currently does not have any native scrubbing feature ?
