### ISSUE TITLE
docker version and info in a more detailed way

### ISSUE THREAD

**Issue by 111andre111** [elastic/ece-support-diagnostics#96]
Having the docker version and docker info would be much better consumable if output to a json file in addition in certain use cases because it contains in depth information like about for containerd or runc versions.
These commands are:
```
  docker info --format '{{json .}}' > docker/info.json
  docker version --format "{{json .}}" > docker/version.json
```

**Comment by jguay** [comment]
I think we should park/close this for now, but feel free to send a commit or we can discuss as we are working on something

Golang version outputs docker info in json already https://github.com/elastic/ece-support-diagnostics/blob/v0/collectors/docker/docker-collector.go#L69 (beside the fact it's missing `docker stats` at the moment) and we are investigating moving to golang as bash version has reached a point where we'll either need `jq` or some libraries to parse json to move forward
